postgresql: # 容器的名称
  image: sameersbn/postgresql:9.4-12 # 使用的镜像及版本
  environment: # 容器的环境变量，相当于docker run命令中的--env，list
    - DB_NAME=redmine_production
    - DB_USER=redmine
    - DB_PASS=password

redmine:
  image: sameersbn/redmine:3.2.0-4
  links: # 互联其他容器，相当于--link postgresql:postgresql
    - postgresql:postgresql
  ports: # 发布端口号，相当于--publish 10083:80
    - "10083:80"
  environment:
    - REDMINE_PORT=10083